# CONFIG 

drone_velocity: 31.3
drone_battery: 1800000000000
drone_launch_time: 0
drone_recover_time: 0
drone_service_time: 0
drone_capacity: 100000000000000.0

truck_velocity: 11.2
truck_service_time: 0
